name: CI/CD Main

on:
  push:
    branches:
      - main

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore DevOpsDemo.Api/DevOpsDemo.Api.csproj

      - name: Build
        run: dotnet build DevOpsDemo.Api/DevOpsDemo.Api.csproj --no-restore --configuration Release

      - name: Test
        run: dotnet test DevOpsDemo.Tests/DevOpsDemo.Tests.csproj --no-build --v

      - name: Build Docker image
        run: docker build -t devops-demo .

      # Push i deploy można dodać później, np. do Azure Container Registry
